events {
    worker_connections 1024;
}


http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;


    # Main server block
    server {
        listen 80;
        server_name localhost;
        root /home/prasiddha/assignment/week2/webapp;
        index index.html;


        # Serve static files
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
